disabled_rules: # Rules to be ignored on the default linting
  - trailing_whitespace
  - vertical_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods